source 'https://rubygems.org'
ruby '2.5.1'

gem 'pry'
gem 'rubocop', '~> 0.57.2'
gem "relaxed-rubocop"
gem 'dotenv-rails', groups: [:development, :test]
gem 'dotenv'
gem 'rake'
gem 'rspec'
gem 'twitter'
gem 'nokogiri'
gem 'watir'
gem 'selenium-webdriver'
gem 'httparty'
gem 'google_drive'
gem 'json'
gem 'colorize'
gem 'fileutils'
gem 'mail'
gem 'gmail'
gem 'googleauth'
gem "spreadsheet"
gem 'csv'